spring.application.name=job-board-scraper

# --- RAPIDAPI CONFIG ---
spring.profiles.include=local

# --- CONFIGURAZIONE DATABASE ---
spring.datasource.url=${DB_URL:jdbc:h2:mem:job_scraper_db}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true